"""fix bug

Revision ID: 349a93e51420
Revises: 69d7685f16c1
Create Date: 2022-05-22 21:06:53.988650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349a93e51420'
down_revision = '69d7685f16c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
